import React from "react";
import MainHeading from "../../MainHeading";
import KeyFeatures from "../StandaloneProducts/SolutionReuseCom/KeyFeatures";
import about_13_1 from "../../../assets/img/normal/about_13_1.jpg";
import about_13_2 from "../../../assets/img/normal/about_13_2.jpg";
import about_13_3 from "../../../assets/img/normal/about_13_3.jpg";
import SolAbout4 from "../StandaloneProducts/SolutionReuseCom/SolutionAbout/SolAbout4";
import OurExpertise from "../StandaloneProducts/SolutionReuseCom/OurExpertises/OurExpertise";
import AccessControlIcon from "../../../Imges/QblockIcon/AccessControlIcon.jpg";
import TalkToAbout1 from "../StandaloneProducts/SolutionReuseCom/TalkToAboutAnyQuestion/TalkToAbout1";
import VersionControlIcon from "../../../Imges/QblockIcon/VersionControlIcon.jpg";
import DocumentsStorageIcon from "../../../Imges/QblockIcon/DocumentsStorageIcon.jpg";
import DocumentsRetrievalIcon from "../../../Imges/QblockIcon/DocumentsRetrievalIcon.jpg";
import WorkflowAutomationIcon from "../../../Imges/QblockIcon/WorkflowAutomationIcon.jpg";
import AuditTrailsIcon from "../../../Imges/QblockIcon/AuditTrailsIcon.jpg";
import "swiper/css";
import "swiper/css/pagination";
const testimonials = [
  {
    text: "“DSS optimizes crop procurement by helping buyers choose the best time to purchase, the optimal quantity, and the best price, while ensuring they stay within the planned budget for highly efficient procurement.”",
    img: DocumentsStorageIcon,
    name: "Procurement Optimization",
    designation: "",
  },
  {
    text: "“DSS analyzes economic factors, providing monthly procurement models and purchase charts, making it easier for buyers to make informed decisions and optimize their strategies for highly cost-effective crop procurement.”",
    img: VersionControlIcon,
    name: "Monthly Procurement Model",
    designation: "",
  },
  {
    text: "“DSS ensures buyers know the best time to buy crops, the right quantity, and the most economical price, helping them stay within budget and plan procurement with greater efficiency and better accuracy.”",
    img: AccessControlIcon,
    name: "Economical Procurement",
    designation: "",
  },
  {
    text: "“The system simplifies crop procurement by focusing on economic factors, providing a clear model to help buyers make decisions based on the most cost-effective time and price for their specific needs.”",
    img: DocumentsRetrievalIcon,
    name: "Simplified Buying Procedure",
    designation: "",
  },
  {
    text: "“DSS provides valuable insights into the crop procurement process, analyzing market trends and economic factors, helping buyers ensure they purchase at the most economical price and at the right optimal time.”",
    img: WorkflowAutomationIcon,
    name: "Critical Insights",
    designation: "",
  },
  {
    text: "“The platform generates detailed procurement models and charts, helping buyers assess purchases at both distributed and cumulative levels, ensuring better planning, decision-making, and effective optimization in the procurement process.”",
    img: AuditTrailsIcon,
    name: "Procurement Insights & Charts",
    designation: "",
  },
];

const ExpertiseArray = {
  heading: "AgRisk Decision Support System",
  para: "AgRisk DSS enhances the decision-making process for crop procurement by providing insights into the best purchasing time, optimal quantity, and the best price, ensuring better financial planning and crop management.",
  keyPoints: [
    { name: "Optimal Procurement Timing", per: "95%" },
    { name: "Economical Price Management", per: "98%" },
    { name: "Budget Coherence", per: "97%" },
    { name: "Improved Decision Making", per: "96%" },
    { name: "Procurement Analytics", per: "99%" },
  ],
};

const TalkToAbout1Array = [
  {
    question: "How does DSS optimize crop procurement?",
    answer:
      "DSS provides insights into the best time to buy crops, the optimal quantity to procure, and the most cost-effective price, helping buyers make informed decisions and stay within their budget.",
  },
  {
    question: "How does the system help with pricing decisions?",
    answer:
      "DSS analyzes market trends and crop data to recommend the best price for procurement, ensuring that buyers purchase crops at the most economical rates while adhering to budget limits.",
  },
  {
    question: "What is the significance of the procurement model?",
    answer:
      "The procurement model generated by DSS provides a detailed chart of distributed and cumulative purchases, helping buyers track their progress and make better purchasing decisions each month.",
  },
  {
    question: "Can DSS be used for various crops?",
    answer:
      "Yes, DSS is designed to optimize procurement for multiple crops across the nation, focusing on the economical aspects and ensuring that buyers can apply it to their specific crop needs.",
  },
];

const aboutData4 = [
  {
    id: 1,
    title: "AgRisk – Decision Support System",
    secTitle: "Crop Procurement Optimization",
    description:
      "AgRisk Decision Support System optimizes crop procurement by analyzing economic aspects, providing a detailed model of when to buy, how much to buy, and at what price, ensuring buyers get the best deal while staying within budget.",
    checklist: [
      ["Procurement Timing", "Price Optimization"],
      ["Budget Coherence", "Informed Decision Making"],
    ],
    contactLink: "contact.html",
    images: [about_13_1, about_13_2, about_13_3],
  },
];

const DecisionSupportSystemPage = () => {
  return (
    <div className="theme-blue3">
      <MainHeading
        title="Decision Support System"
        subtitle="Decision Support System"
        breadcrumbs={[{ label: "Home", link: "/" }, { label: "Solution" }]}
        marginBottom="70px"
      />
      <SolAbout4 aboutData={aboutData4} />
      <KeyFeatures testimonials={testimonials} />
      <OurExpertise ExpertiseArray={ExpertiseArray} />
      <TalkToAbout1 TalkToAbout1Array={TalkToAbout1Array} />
    </div>
  );
};

export default DecisionSupportSystemPage;
